[package]
name = "knight"
version = "0.1.0"
authors = ["Anselmo Sampietro <ans.samp@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "94c41840680afd414acb1195889bb88588901100" }
glam = "0.13.0"
tiled = "0.9.3"
